### ISSUE TITLE
No projects are listed by the subl command

### ISSUE THREAD

**Issue by leugengroot** [Cloudstek/alfred-sublime#1]
macOS Catalina 10.15.2
Alfred 4.07 [1113] (with paid Powerpack)
NodeJS v12.3.1
Sublime3.2.2 (unregisterd)
Sublime Project Manager for Sublime Text 3 0.7.18 installed

Workflow installed via npm.

In the folder
> ~/Library/Application Support/Sublime Text 3/Packages/User/Projects

are three files
* recent.json
*  testprojectName.sublime-workspace
*  testprojectName.sublime-project

When I start the Workflow with "subl" I still don't get my Project listed.

**Comment by ibrychgo** [comment]
Having same problem here. Project files are in the correct path. Package Manager is installed. No projects appear.

With debug turned on there's an error:

```
Error: Cannot find module '@cloudstek/cache'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)

```
I went and installed cloudstek/cache via NPM but the error still appears.

**Comment by dotvhs** [comment]
For me, the issue was that I didn't have "Sublime Text 3" folder under "Application Support", instead I had just "Sublime Text" folder. So I created a symlink and now it works flawlessly.
